(define (timed-prime-test n)
  (newline)
  (display n)
  (display
    (start-prime-test n (runtime))
    )
  (start-prime-test n (runtime))
  )
(define (start-prime-test n start-time)
  (cond ((prime? n) (= 1 1))
        (else (= 1 0))
    )
  )
(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time)
  )
(define (prime? n)
  (= (smallest-divisor n) n) 
  )
(define (smallest-divisor n)
  (find-divisor n 2)
  )
(define (find-divisor n test-divisor)
  (cond ((> (square test-divisor) n) n)
        ((divides? test-divisor n) test-divisor)
        (else (find-divisor n (+ test-divisor 1)))
        )
  )
(define (divides? t n)
  (= (remainder n t) 0)
  )
(define (search-for-primes start-number)
  (if (timed-prime-test start-number)
    (= 1 1 )
    (search-for-primes (+ start-number 2))
    )
  )

(search-for-primes 1001)
(search-for-primes 10001)
(search-for-primes 100001)
;崩溃中
