(load "sum.scm")
(load "cube.scm")

(define (simpson f a b n)
  (define h (/ (- b a) n))
  (define (yk k)
    (f (+ a (* k h)))
    )
  (define (term k)    
    (cond ((not (even? k))  (* 4 (yk k)))
          ((= 0 k) (yk k))
          ((= n k) (yk k))
          (else (* 2 (yk k)))
          )
    )
  (* (/ h 3) (sum term 0 inc n))
  )

(simpson cube 0. 1 100)
(simpson cube 0. 1 1000)
(simpson cube 0. 1 10000)
